services:
  next:
    restart: on-failure
    build: ./
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync+restart
          path: ./
          target: /app
          ignore:
            - ./node_modules
        - action: rebuild
          path: ./package.json
  postgresql:
    image: postgres:alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - next-commerce-data:/var/lib/postgresql/data

volumes:
  next-commerce-data:
