version: '3.8'

services:
  next:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
  postgresql:
    # Postgres image with PostGIS extension for geospatial data:
    image: postgres:alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - next-commerce-data:/var/lib/postgresql/data

volumes:
  next-commerce-data:
